name: Java checks

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Spotless check
        run: mvn --batch-mode --update-snapshots spotless:check
      - name: Package fake-backend
        run: mvn --projects instrumentation-tests/utils/fake-backend package
      - name: Package and install plugin
        run: mvn --projects app-instrumenter package && mvn --projects app-instrumenter install
      - name: Test apache-http-test-app
        run: ./instrumentation-tests/scripts/test-apache-http-app.sh
      - name: Test spring-test-app
        run: ./instrumentation-tests/scripts/test-spring-app.sh
